### ISSUE TITLE
Fatal on matches_type_structure() with container in shape in TS, but not value

### ISSUE THREAD

**Issue by genych** [hhvm/type-assert#10]
Basic example:

```
class A
{
    const type Something = shape('ints' => Container<int>);
}

\FredEmmott\TypeAssert\TypeAssert::matchesTypeStructure(
    type_structure(A::class, 'Something'), []);
```
Result:

> Catchable fatal error: Argument 2 passed to FredEmmott\TypeAssert\PrivateImpl\TypeStructureImpl::assertValueTypes() must implement interface HH\KeyedTraversable, null given in …/vendor/fredemmott/type-assert/src/PrivateImpl/TypeStructureImpl.php on line 179

HipHop VM 3.12.0-dev

**Comment by fredemmott** [comment]
I'll update the readme - 3.12 is no longer supported, either by this library or the HHVM team. There are unfixed security issues unless you are on 3.18 or newer.

**Comment by fredemmott** [comment]
Does sttill repro on 3.21 though

**Comment by fredemmott** [comment]
Sorry, I'd tag a new release, but can't run the tests on travis given it looks like composer's having network issues (https://gist.github.com/fredemmott/bad82067387f649b2bc2d782758c5cc8)

**Comment by fredemmott** [comment]
nm, seems to have fixed itself
