### ISSUE TITLE
Evaluates empty arrays as NULL causing unexpected exceptions

### ISSUE THREAD

**Issue by sbilstein** [hhvm/type-assert#15]
```
use \FredEmmott\TypeAssert\TypeAssert;

type my_shape_t = shape(
		'one' => bool,
		'two' => array
	);

$my_array = array ('one' => true, 'two' => array());

$shape = new ReflectionTypeAlias('my_shape_t');
$type_structure = $shape->getResolvedTypeStructure();

$assertion = TypeAssert::matchesTypeStructure($type_structure, $my_array);

#
# Throws this exception
# Fatal error: Uncaught exception 'FredEmmott\TypeAssert\IncorrectTypeException' with message 'Expected not-null, got null' in ~/code/include/type-assert/TypeAssert.php:72
#
```
The above example, I think, should evaluate correctly but the 'two' field gets read as null even though it is an empty array.

**Comment by fredemmott** [comment]
Thanks for the report, I should be looking into this today or tomorrow

**Comment by fredemmott** [comment]
Fixed for the next release. I've not checked on the current one, but I suspect it's the same cause:

It's not the empty array that's problematic - it's using `array` as the type without generics, i.e. not `array<type_of_value_goes_here>` or `array<type_of_key, type_of_value>`

**Comment by sbilstein** [comment]
thanks so much for the quick turnaround!

**Comment by fredemmott** [comment]
@sbilstein : the next version (3.x) will have some fairly major changes and require 3.21; is that requirement likely to be a problem for you/Slack? If so, I can roll an equivalent change into a 2.x release

**Comment by sbilstein** [comment]
@fredemmott That "workaround" is good enough for me/slack at the moment. Thanks!

**Comment by fredemmott** [comment]
You might also be interested in the JSON_FB_HACK_ARRAYS option for json_decode , depending on where you're getting the data from :)
