### ISSUE TITLE
Remove tuple/shape coercion from assert path

### ISSUE THREAD

**Issue by fredemmott** [hhvm/type-assert#18]
We allow either arrays or vecs for tuples, and arrays or dicts for shapes. We should require they match the current runtime.

This makes migration slightly harder, but the 'typeassert may return a different value' thing it creates leads to more problems.

**Comment by fredemmott** [comment]
Will leave this as-is until tuples and shapes change their implementation.

**Comment by lexidor** [comment]
#48 Related issue
