### ISSUE TITLE
Missing support for Hack arrays

### ISSUE THREAD

**Issue by HRMsimon** [hhvm/type-assert#2]
Probably not coming out until 3.17, but is in the nightlies already.

```
vendor/fredemmott/type-assert/src/PrivateImpl/TypeStructureImpl.php:25:13,23: Switch statement nonexhaustive; the following cases are missing: OF_VEC, OF_KEYSET, OF_DICT (Typing[4019])
  /tmp/hh_server/hhi_c9b76cf/typestructure.hhi:16:6,22: Enum declared here
```

**Comment by fredemmott** [comment]
Thanks; for now, it seems like it'll be best to throw an exception on these as they're basically not supported in OSS HHVM (especially library support) and require an experimental flag passing to the typechecker. Would an exception fit your needs (and make the switch statement exhaustive), or is there some external project to work around the current limitations?

**Comment by HRMsimon** [comment]
An exception would work fine. We're not using them, just getting the error from Hack because I'm weird and like to use master instead of stable releases ;)

**Comment by fredemmott** [comment]
Is there anything in your .hhconfig? The error you're reporting makes sense, but I can't reproduce it with the nightlies :/

**Comment by HRMsimon** [comment]
The only thing in there's a `user_attribute` list. Removing it still gives the error.

It could be because I'm building from source, rather than using one of the packages.

**Comment by fredemmott** [comment]
https://github.com/hhvm/packaging/issues/147
