### ISSUE TITLE
matches_type_structure() too restrictive on HH\Container with arrays

### ISSUE THREAD

**Issue by genych** [hhvm/type-assert#20]
Hi

Another issue with matches_type_structure() (\TypeCoerce\match_type_structure as well):

```
class X
{
  const type Arr = Container<mixed>;
}

\Facebook\TypeAssert\matches_type_structure(type_structure(X::class, 'Arr'), []);
```

Throws `Facebook\TypeAssert\IncorrectTypeException' with message 'Expected type 'HH\Container<T>', got type 'array'`

But it shouldn't, right? _In addition to Hack collections, PHP arrays are Containers_ (https://docs.hhvm.com/hack/reference/interface/HH.Container/)

**Comment by fredemmott** [comment]
Looks like the special interfaces aren't supported by is_a :'(


```
hphpd> $x = []
hphpd> =$x instanceof Container
true
hphpd> =is_a($x, Container::class)
false
hphpd> =is_a('foo', Stringish::class)
false
```

**Comment by genych** [comment]
Kudos for great support!
