### ISSUE TITLE
Support for generic types in assertMatchesTypeStructure?

### ISSUE THREAD

**Issue by eryi** [hhvm/type-assert#3]
Is it possible to get TypeStructure for for generic types?

**Comment by fredemmott** [comment]
If the types are resolved in the alias, it will work fine; do you mean something like this instead?

``` Hack
<?hh

class Foo<T> {
  type X = Vector<T>;
}

TypeAssert::assertMatchesTypeStructure(
  type_structure(Foo:class, 'X'), // what's T?
  $some_value,
);
```

I don't think this is supported by HHVM, but if it's what you're looking for, I can ask.

**Comment by fredemmott** [comment]
Closing, unclear what's wanted.
