### ISSUE TITLE
[BC broken] Exception type for `DictSpec::assertType()` changed between 3.6.1 and 3.6.2

### ISSUE THREAD

**Issue by lexidor** [hhvm/type-assert#36]
In my attempt to allow slackhq/hack-json-schema to run on hhvm 4.27, I found that the newer hhvm versions failed the test suite. After hours of debugging I pinned it down on this concept.

```HACK
use namespace Facebook\TypeSpec;
use namespace Facebook\TypeAssert;

<<__EntryPoint>>
async function main_async(): Awaitable<void> {
  require_once __DIR__.'/vendor/autoload.hack';
  Facebook\AutoloadMap\initialize();

  try {
    $spec = TypeSpec\dict(TypeSpec\string(), TypeSpec\mixed());
    $spec->assertType([1, 2, 3, 4]);
  } catch (TypeAssert\TypeCoercionException $t) {
    echo "You are running TypeAssert 3.6.1\n";
  } catch (TypeAssert\IncorrectTypeException $t) {
    echo "You are running TypeAssert 3.6.2\n";
  }
}
```

In [`ObjectConstraint::check()`](https://github.com/slackhq/hack-json-schema/blob/master/src/Constraints/ObjectConstraint.php#L28) they catch TypeCoercionException to detect and fallback to an array check instead. This exception is now no longer caught. This caused a handful of test failures.

**Comment by lexidor** [comment]
It appears like this change was made intentionally. I'll rewrite the code in hack-json-schema to work with both exception types.

_Commit by @fredemmott_
https://github.com/hhvm/type-assert/commit/9f0f4975a5dee0bd9e7e4e47473668a2d0976f9c

**Comment by fredemmott** [comment]
The intent is that TypeCoercionException should never be thrown by assertType, and IncorrectTypeException should never be thrown by coerceType

**Comment by lexidor** [comment]
I have updated the affected code in hack-json-schema. Now it will now work with both exception types. You are right about throwing IncorrectTypeException. It just broke some software out in the wild. Closing.
