### ISSUE TITLE
Missing support for new hack arrays

### ISSUE THREAD

**Issue by mofarrell** [hhvm/type-assert#4]
https://github.com/fredemmott/type-assert/blob/master/src/PrivateImpl/TypeStructureImpl.php is missing cases in the switch for the new hack array types (vec, keyset and dict).  This makes the project fail type checking as the switch statement is non-exhaustive.

**Comment by mofarrell** [comment]
Old version.  Saw the comment in TypeStructureImpl.php

**Comment by fredemmott** [comment]
Yeah - v1.0 includes the fix, you're probably on 0.2
