### ISSUE TITLE
Use directly with a shape

### ISSUE THREAD

**Issue by vlechemin** [hhvm/type-assert#5]
Hello,

It's a great lib! I'm wondering if it would be possible to use it directly with a shape, here is my usecase:

```hack
$result = $db->table->find([
  'id' => 1,
], shape(
  'id' => int,
  'data' => string,
));
```

and `$result` would be typed with the projection. (more exactly `array<T>`)

Thanks a lot :)

**Comment by fredemmott** [comment]
Sorry, no:
 - HHVM and Hack don't provide a way to support it.
 - your proposed syntax is ambiguous: does `shape('foo' => Bar)` mean a shape type with element foo that is a Bar, or a shape instance with element foo that contains the same value as the global constant Bar?

**Comment by fredemmott** [comment]
You might want to consider abstracting away your DB reads anyway; if you do that, it would make sense to have the row shape defined as a type.

**Comment by vlechemin** [comment]
Thanks for your quick answer, what I meant was to have a type as value, to be able to pass the return type to a function directly as an anonymous shape.
I agree that it's not the best way to do it, but having the projection/typing close to the query seemed to be more clear.
Thank you for your advice!

**Comment by fredemmott** [comment]
cc @jesseschalken - https://gist.github.com/jesseschalken/babe293ef421da3a7d71fa3e35325002#file-hacktypes-php-L323 might be a good alernative here

**Comment by jesseschalken** [comment]
If you just want to cast/assert, you could pass a closure that accepts the fetched row (whatever the type of that is, say `array<string, ?string>`) and casts/asserts it into some type:

```php
$result = $db->table->find([
  'id' => 1,
], $row ==> shape(
  'id' => (int) $row['id'],
  'data' => (string) $row['data'],
));
```

So rather than defining a type and reflecting on that type to do an assertion/conversion, define the code that does the the assertion/conversion and let Hack infer the type from it. `find` would then be `find<T>(.., (function (array<string, ?string>): T)): T`.

Although at that point you might as well just return `Vector<array<string, ?string>>` and call `->map`.

**Comment by vlechemin** [comment]
Thank you both for your help!
What I tried to do @jesseschalken, was to ask for a projection of the query (by reflection of the shape) and at the same time, type the return value `$result`.
I thought having shapes/types as first class value like lambdas was a good idea, but what fredemmot said makes sense.
On another point, how complex would it be to use directly `self::TAPIResponse` instead of  `type_structure(self::class, 'TAPIResponse')`? It's probably due to the downside of an untyped language, as it's already the case with fun, inst_meth...

**Comment by fredemmott** [comment]
Not supported by HHVM/Hack - type constants aren't values, the type structure is the closest thing
