### ISSUE TITLE
QQ: Is it intentional that ShapeSpec drops unknown keys when coercing to a shape without optional fields?

### ISSUE THREAD

**Issue by lexidor** [hhvm/type-assert#62]
https://github.com/hhvm/type-assert/blob/master/src/TypeSpec/__Private/ShapeSpec.hack

Passing a dict with keys a and b to ShapeSpec coerceType of `shape('a' => string)` drops `b`. Is this intentional? The assert code path fails loudly for this.

**Comment by fredemmott** [comment]
Yes; a closed shape may not contain extra fields. This matches the typechecker and runtime behavior for `is`, and the result of an assert/coerce should pass is/as.

```
hphpd> = shape('a' => '123') is shape('a' => string)
true
hphpd> = shape('a' => '123', 'b' => 'foo') is shape('a' => string)
false
hphpd> = shape('a' => '123', 'b' => 'foo') is shape('a' => string, ...)
true
```
