### ISSUE TITLE
3.18 Breaks things :(

### ISSUE THREAD

**Issue by HRMsimon** [hhvm/type-assert#7]
```
File "/builds/HRMWEB/easyEMPLOYER/vendor/fredemmott/type-assert/src/TypeAssert.php", line 81, characters 9-30:
'instanceof' cannot be used on a generic classname because types are erased at runtime (Typing[4162])
```

I just added `// UNSAFE` in the method, but you may have a nicer way of doing it (like a `FIXME`, I was just lazy). Was hoping that Hack would've been fixed before the release, but apparently not.

**Comment by fredemmott** [comment]
Fix will be tagged once travis finishes :)

**Comment by fredemmott** [comment]
https://github.com/fredemmott/type-assert/commit/38460b438ca85701585abe471d944c678d242847

**Comment by fredemmott** [comment]
A wild v1.1 appears - it's super effective!

**Comment by HRMsimon** [comment]
Hooray! :)
